### ISSUE TITLE
Модифицировать класс фейковой базы

### ISSUE THREAD

**Issue by Chocco-Crokko** [ilyamoskalev/Apoj_backend#6]
- [x] Сделать вместо массива `User[]` отображение `Map<id, User>` 

- [x] Айдишники хранить в long

- [x] Сделать проверку на уникальность почты

- [x] (Очень желательно!) Сделать интерфейс базы данных. Очень пригодится, когда будете переходить на нефейковую базу

**Comment by ilyamoskalev** [comment]
done
