### ISSUE TITLE
Добавить шифрование паролей

### ISSUE THREAD

**Issue by Chocco-Crokko** [ilyamoskalev/Apoj_backend#7]
- [x] Прочитать про `Bean`'ы `Spring`'а. Также нужно почитать о Dependency Injection

- [x] В коде для шифрования паролей должен использоваться интерфейс `PasswordEncoder`. В `Application` должен быть бин, который возвращает уже конкретную реализацию энкодера

**Comment by ilyamoskalev** [comment]
done
